name: Checkout repository
on: push

jobs:
  checkout-repo-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: List files
        run: ls -la
  checkout-repo-manually:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout manually the repository
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout master
      - name: List files
        run: ls -la 
