name: Devel

on:
  push:
    branches:
      - develop

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
