name: Display Shell
on: push

defaults:
  run:
    shell: bash

jobs:
  display_shell:
    runs-on: ubuntu-latest
    steps:
      - name: Display Shell
        run: |
          echo $SHELL
          pwd
          ls -la
      - name: Show commit sha and repository and workspace
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE

