name: Expressions
on: [issues, pull_request]

jobs: 
  print_issue_context:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issues' }}
    steps:
      - name: Print issue context
        run: echo ${{ toJson(github) }}
  get_labels_from_issue:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issues' }}
    steps:
      - name: Print all labels with contains if issue is a bug
        if: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
        run: echo ${{ join(github.event.issue.labels.*.name, ', ') }}
        