name : First workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: echo a multiline
        run: |
          node -v
          npm -v
  
  parallel-job:
    runs-on: macos-latest
    steps:
      - name: show sw version
        run: sw_vers
      - name: show xcode version
        run: xcodebuild -version
      
  dependant-job:
    runs-on: ubuntu-latest
    needs: [run-shell-commands]
    steps:
      - name: show linux version
        run: uname -a
      - name: show ubuntu version
        run: lsb_release -a