name: Testing functions

on: [push]

jobs:
  test_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Check result functions
        run: |
          echo ${{ contains('hello', 'll') }}
          echo ${{ starsWitch('hello', 'he') }}
          echo ${{ endsWitch('hello', 'o') }}
          echo ${{ format('hello {0} {1} {2}', 'world', '!', '!') }}
